# Generated by Django 4.2 on 2023-04-30 04:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comunidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('fecha_salida', models.DateField()),
                ('categoria', models.CharField(choices=[('peliculas', 'Peliculas'), ('musica', 'Musica'), ('series', 'Series'), ('videojuego', 'Videojuego'), ('documentales', 'Documentales'), ('juegos_de_mesa', 'Juegos de mesa'), ('cocina', 'Cocina'), ('deportes', 'Deportes'), ('tv', 'TV'), ('arte', 'Arte'), ('fotografias', 'Fotografias'), ('libros', 'Libros'), ('carreras', 'Carreras'), ('pelea', 'Pelea'), ('otro', 'Otro')], max_length=255)),
                ('empresa', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('valoracion', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')])),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('comunidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppBase_comunidad')),
            ],
        ),
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='avatares')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
