# Generated by Django 4.2 on 2023-04-30 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBase', '0002_remove_comunidad_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunidad',
            name='categoria',
            field=models.CharField(choices=[('peliculas', 'Peliculas'), ('musica', 'Musica'), ('series', 'Series'), ('videojuego', 'Videojuego'), ('documentales', 'Documentales'), ('juegos_de_mesa', 'Juegos de mesa'), ('cocina', 'Cocina'), ('deportes', 'Deportes'), ('tv', 'TV'), ('arte', 'Arte'), ('fotografias', 'Fotografias'), ('libros', 'Libros'), ('carreras', 'Carreras'), ('pelea', 'Pelea'),('tower_defense', 'Tower Defense')], max_length=255),
        ),
    ]
