# Generated by Django 4.2 on 2023-05-12 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBase', '0004_tema_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunidad',
            name='categoria',
            field=models.CharField(choices=[('peliculas', 'Peliculas'), ('musica', 'Musica'), ('series', 'Series'), ('videojuego', 'Videojuego'), ('documentales', 'Documentales'), ('juegos_de_mesa', 'Juegos de mesa'), ('cocina', 'Cocina'), ('deportes', 'Deportes'), ('tv', 'TV'), ('arte', 'Arte'), ('fotografias', 'Fotografias'), ('libros', 'Libros')], max_length=255),
        ),
]
